[timer]
ignore_idle_inhibitors = false
idle_timeout = 240
short_break_timeout = 1200
short_break_duration = 30
long_break_timeout = 7200
long_break_duration = 900

[notification]
show_progress_bar = true
minimum_update_delay = 1
