[general]
import = [
    "~/.config/alacritty/colors.toml"
]

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9

[font]
size = 12

[cursor]
style = { shape = "Beam", blinking = "On"}
